apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: npm
spec:
  steps:
    - args:
        - npm install
      command:
        - /bin/sh
        - '-c'
      image: 'registry.redhat.io/ubi8/nodejs-10:latest'
      name: npm-install
      workingDir: /workspace/output

    - args:
        - npm run build
      command:
        - /bin/sh
        - '-c'
      image: 'registry.redhat.io/ubi8/nodejs-10:latest'
      name: build
      resources: {}
      workingDir: /workspace/output

    - args:
        - cp -R ./dist/* $(workspaces.output.path)
      command:
        - /bin/sh
        - '-c'
      image: 'registry.redhat.io/ubi8/nodejs-10:latest'
      name: copy-dist
      resources: {}
      workingDir: /workspace/output
  workspaces:
    - name: output
