apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: modern-ui-checkfolder-only
spec:
  params:
    - name: app-name
      type: string
      description: Application name
      default: modern-ui
    - name: git-url
      type: string
    - name: git-revision
      type: string

  tasks:

    - name: fetch-repository
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: app-binary
      params:
        - name: url
          value: $(params.git-url)
        - name: subdirectory
          value: ""
        - name: deleteExisting
          value: "true"
        - name: revision
          value: $(params.git-revision)

    - name: check-folders
      runAfter: 
        - fetch-repository
      taskRef:
        kind: Task
        name: check-folders
      workspaces:
        - name: output
          workspace: app-binary


  workspaces:
    - name: app-binary
